export const SELECT_CITY = "SELECT_CITY";
export const CREATE_HISTORY = "CREATE_HISTORY";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const DELETE_HISTORY = "DELETE_HISTORY";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
