export const SELECT_CITY = "SELECT_CITY";
export const CREATE_HISTORY = "CREATE_HISTORY";
export const UPDATE_HISTORY = "UPDATE_HISTORY";
export const DELETE_HISTORY = "DELETE_HISTORY";
export const CURRENT_WEATHER = "CURRENT_WEATHER";
export const FIVE_DAYS_WEATHER = "FIVE_DAYS_WEATHER";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";


