export const SELECT_CITY = "SELECT_CITY";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_FIVE_DAYS_WEATHER = "GET_FIVE_DAYS_WEATHER";
export const CREATE_HISTORY = "CREATE_HISTORY";
